apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.nameOverride}}"
spec:
  type: NodePort
  selector:
    app: "{{.Values.nameOverride}}"
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
