apiVersion: v1
kind: Service
metadata:
  name: event-hub-site-service
spec:
  selector:
    app: event-hub-site
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer
